Add controllers
Holy-Raven/java-shareit pull request #1
Opened 2023-06-06 17:42 UTC by Holy-Raven

2023-06-07 20:14 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо

1) Логи во всех методах контроллеров давай добавим
2) Поправить что отметил
3) Рекомендация: рекомендую создавать больше исключений которые будут более узко специализирован

Буду ждать с правками =)

2023-06-07 20:14 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    static long newId = 1;
private final может быть?

2023-06-07 20:14 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    static long newId = 1;
final лишнее само собой

2023-06-07 20:14 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
модификаторы доступа?

2023-06-07 20:14 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
>  public class ItemRequestDto {
модификаторы доступа?

2023-06-07 20:14 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +public class ItemRequest {
модификаторы доступа?

2023-06-07 20:14 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +    static long newId = 1;
поправить

2023-06-07 20:14 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +                throw new RuntimeException("there is already a user with an email " + user.getEmail());
Создай специальные исключения для таких ситуаций

2023-06-08 13:44 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    static long newId = 1;
исправила

2023-06-08 13:44 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
да, баловалась с аннотациями, изначально они были. Поправила

2023-06-08 13:45 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +public class ItemRequest {
Поправила

2023-06-08 13:45 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +    static long newId = 1;
Поправила

2023-06-08 14:32 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +                throw new RuntimeException("there is already a user with an email " + user.getEmail());
Для email создала. 
И notfound у меня теперь универсальное исключение, показывает какой именно объект не найден.

2023-06-09 14:21 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет

2023-06-09 14:21 UTC, krylov-sergey-sergeevich commented on pom.xml
> +            <version>20.1.0</version>
версию лучше в проперти сдвинуть

2023-06-09 14:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto updateItem(@RequestHeader("X-Sharer-User-Id") long userId,
"X-Sharer-User-Id" - я бы вынес в константу

2023-06-09 14:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto updateItem(@RequestHeader("X-Sharer-User-Id") long userId,
тк везде дублируется

2023-06-09 14:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +    public NotFoundException(Class<?> entityClass, String message) {
понимаю что удобно класс передавать, но не самая лучшая практика

2023-06-15 13:48 UTC, merged