Add bookings
Holy-Raven/java-shareit pull request #2
Opened 2023-06-22 15:12 UTC by Holy-Raven

2023-06-23 14:16 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо - давай поправим и будет зачет =)

2023-06-23 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  public class Booking {
private ко всем полям

2023-06-23 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingOutDto addBooking(@RequestHeader("X-Sharer-User-Id") Long userId,
"X-Sharer-User-Id" давай вынесем в константы

2023-06-23 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
Смысл в компоненте делать статичные методы? Тогда уж или убирать компонент аннотацию или не делать статичные функции

2023-06-23 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +@RequiredArgsConstructor
@Transactional(readOnly = true)

2023-06-23 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    Long itemId;
private

2023-06-23 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            bookingState = State.valueOf(state);
это можно спрятать внутрь метода который будет в State

2023-06-23 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/dto/BookingOutDto.java
> +    long id;
private Long

2023-06-23 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
>  public class ItemMapper {
про статик аналогично

2023-06-23 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/User.java
> +    private long id;
Long

2023-06-23 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
>  public class UserMapper {
Статик

2023-06-23 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        if (!userRepository.existsById(userId)) {
Как будто бы дубль кода

2023-06-24 05:33 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  public class Booking {
исправила

2023-06-24 05:39 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingOutDto addBooking(@RequestHeader("X-Sharer-User-Id") Long userId,
хорошо

2023-06-24 05:41 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
убрала аннотацию

2023-06-24 05:47 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +@RequiredArgsConstructor
добавила

2023-06-24 05:47 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    Long itemId;
исправила

2023-06-24 05:48 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/booking/dto/BookingOutDto.java
> +    long id;
исправила

2023-06-24 05:54 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            bookingState = State.valueOf(state);
да. красиво вышло

2023-06-24 05:54 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
>  public class ItemMapper {
убрала аннотацию

2023-06-24 06:05 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/user/User.java
> +    private long id;
исправила

2023-06-24 06:06 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
>  public class UserMapper {
убрала аннотацию

2023-06-24 07:10 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        if (!userRepository.existsById(userId)) {
вынесла в отдельный сервис

2023-06-25 06:53 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-06-25 06:53 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    @Transactional(readOnly = true)
не стоит тк на классе уже стоит

2023-06-25 13:01 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    @Transactional(readOnly = true)
поняла, окей

2023-06-26 14:01 UTC, merged