Add item requests
Holy-Raven/java-shareit pull request #3
Opened 2023-07-06 17:35 UTC by Holy-Raven

Было очень не просто, но я это сделала! Единственно что касается репозиториев, то почти все методы у меня генирируются гибернейтом, потому написала тест только на метод с Query запросом (на такие же методы надо по заданию писать тесты как я поняла).

2023-07-07 19:02 UTC, krylov-sergey-sergeevich requested changes
Привет, отметил что нужно доработать

2023-07-07 19:02 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        User user = userRepository.findById(userId).get();
Может что-то такое:
userRepository.findById(userId)
				.orElseThrow(() -> new IllegalStateException("Wrong user id=" + userId));

Как считаешь?

2023-07-08 07:45 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            item.setRequest(itemRequestRepository.findById(itemDto.getRequestId()).get());
у меня тут реализована проверка методом existById

2023-07-08 07:45 UTC, Holy-Raven commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        User user = userRepository.findById(userId).get();
у меня тут реализована проверка методом existById

2023-07-08 16:21 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу - зачет!

Но на счет улучшения системы методов exists и т.д я бы подумал.

2023-07-09 18:47 UTC, merged